version: 2.1

orbs:
  image-docker: cimg/base@stable

jobs:
  job-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          command: echo hola

workflows:
  wf-hello:
    jobs:
      - job-hello
