version: 2.1

orbs:
  android: circleci/android@2.1.1

jobs:
  build:
    executor:
      name: android/android
      tag: "latest"
    working_directory: ~/project
    steps:
      - checkout
      - android/prepare
      - run:
          name: Build Debug APK
          command: ./gradlew assembleDebug
      - store_artifacts:
          path: app/build/outputs/apk/debug
          destination: apk

workflows:
  build_and_test:
    jobs:
      - build
