version: 2.1

orbs:
  android: circleci/android@2.4.0

jobs:
  build:
    docker:
      - image: cimg/android:2024.01   # Imagen con Android SDK + JDK
    working_directory: ~/project
    steps:
      - checkout

      # Configurar caché de Gradle
      - restore_cache:
          keys:
            - gradle-cache-{{ checksum "build.gradle" }}
            - gradle-cache-{{ checksum "build.gradle.kts" }}
            - gradle-cache-{{ checksum "app/build.gradle" }}
            - gradle-cache-{{ checksum "app/build.gradle.kts" }}
            - gradle-cache-

      # Asegurar permisos de Gradlew
      - run:
          name: Grant Gradlew permissions
          command: chmod +x ./gradlew

      # Descargar dependencias
      - run:
          name: Download dependencies
          command: ./gradlew dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-cache-{{ checksum "build.gradle.kts" }}-{{ checksum "app/build.gradle.kts" }}


      # Compilar proyecto
      - run:
          name: Build Debug APK
          command: ./gradlew assembleDebug

      # Ejecutar tests unitarios
      - run:
          name: Run Unit Tests
          command: ./gradlew testDebugUnitTest

      # Guardar artefactos (APK generado)
      - store_artifacts:
          path: app/build/outputs/apk/debug/
          destination: debug-apk

workflows:
  build_and_test:
    jobs:
      - build